language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - curl -s http://getcomposer.org/installer | php

install:
  - php composer.phar install --no-interaction

before_script:
  - "mysql -e 'create database e2_acceptance;'"
  - "echo \"modules: {config: {Db: {user: 'travis', password: ''}}}\" > codeception.yml"
  - ./run-server &

after_failure:
  - sh -e 'cat tests/_log/*.fail.html'

after_script:
  - find .
  - cat codeception.yml
  - cat vendor/e2/e2/user/settings.psa


script: "vendor/bin/codecept run --debug -vvv"

