language: php

php:
  - 5.4

before_install:
  - curl -s http://getcomposer.org/installer | php

install:
  - php composer.phar install --no-interaction

before_script:
  - "mysql -e 'create database e2_acceptance;'"
  - "echo \"modules: {config: {Db: {user: 'travis', password: ''}}}\" > codeception.yml"
  - php -i
  - ./run-server &

after_failure:
  - cat ./tests/_log/WriteNotPublishPostCept.php.page.fail.html
  - cat ./vendor/e2/e2/user/settings.psa

after_script:
  - find .
  - cat ./codeception.yml
  - cat ./vendor/e2/e2/user/settings.psa


script: "vendor/bin/codecept run --debug -vvv"

